name: release

on:
  push:
    branches: [master]
    paths-ignore:
      - metadata.json
      - .github
      - README.md
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: geertvdc/setup-hub@master

      - name: package and releases
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          ignored="! -path $(pwd) "
          for i in $(cat .templateignore); do
              ignored+="! -name $i "
          done
          files=$(find $(pwd) -maxdepth 1 $ignored)

          mkdir golang
          cp -r $files ./golang

          zip -r golang.zip ./golang;
          openssl sha256 golang.zip | cut -d " " -f2 > golang.zip.sha256

          version=$(jq -r ".version" metadata.json)

          hub release create -m "v$version" "v$version"
          hub release edit -m "" -a golang.zip "v$version"
          hub release edit -m "" -a golang.zip.sha256 "v$version"

      - name: setup git
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: bump version
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          git clean -dfx
          version=$(jq -r ".version" metadata.json | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo $(jq -r ".version = \"$version\"" metadata.json) | jq . > new_metadata.json
          cat new_metadata.json > metadata.json
          git add metadata.json
          git commit -m "Bumped version to $version"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" master
